name = "toolbox-app"
main = "src/index.js"
compatibility_date = "2024-07-20"

[vars]
# Variabel lingkungan jika diperlukan

[env.production]
vars = { ENVIRONMENT = "production" }

# Konfigurasi untuk assets statis
[assets]
binding = "ASSETS"
directory = "./public"